// Code generated by sqlc. DO NOT EDIT.
// source: tasks.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    title, "description", complete
) VALUES (
    $1, $2, $3
) RETURNING id, title, description, complete
`

type CreateTaskParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Complete    string `json:"complete"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask, arg.Title, arg.Description, arg.Complete)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Complete,
	)
	return i, err
}
